### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by pb2888** [SV1CAL/Satellite-FUN#1]
I downloaded it,extracted it then well went to "open" it and NOTHING loads up at all

**Comment by SV1CAL** [comment]
Hi,
Please follow the instructions here (scroll down towards the end ):

https://sv1cal.com/satellite-fun-software/

Regards,
Michael

**Comment by SV1CAL** [comment]
Hi , 
Prior to running the program , have you registered the dll?

In the instructions there is the following information:
####################################################################
Follow the instructions below to install the DJTSatlib.dll.

On 64 bit systems:

First copy the DJTSatlib.dll to your Windows\SysWOW64 folder and 
register the dll being in that folder. This can be done as follows :
Open a cmd window as Administrator --> Start/All Programs/Accessories .
Then Right click and Select “Run as Administrator”.
Then change folder to Windows/SysWow64 by typing :

cd C:\Windows\SysWOW64

Now type:

 regsvr32 DJTSatlib.dll


On 32 bit systems:

Enter the unzipped folder and double-click on “install djtsatlib.bat”. 
This is only needed once, when the program is installed for the first time.
If this does not work try the following:
Copy/paste the dll into Windows/System32 folder and register the dll in there.
This can be done by first opening a cmd window   (Start/All Programs/Accessories). 
On W7 cmd must be opened as admin so Right click and Select “Run as Administrator”
In the cmd window that has just opened, change folder to Windows/System32 
by typing :

cd C:\Windows\System32

Now type:

 regsvr32 DJTSatlib.dll

Important Note:

Windows 7/8/10 users must be administrators to successfully register the dll.
####################################################################################
